version: "3.7"
services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: swiss-qr-bill-server-local-development
        container_name: app
        ports:
            - "80:8080"
        volumes:
            - ./src:/var/www